name:                seocheck
version:             0.0.0.0
github:              "NorfairKing/seocheck"
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - case-insensitive
    - conduit
    - containers
    - envparse
    - html-conduit
    - http-client
    - http-client-tls
    - http-types
    - monad-logger
    - network-uri
    - optparse-applicative
    - path
    - path-io
    - rainbow
    - stm
    - text
    - unliftio
    - unliftio
    - validity
    - xml-conduit
    - yamlparse-applicative

executables:
  seocheck:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - seocheck

tests:
  seocheck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - seocheck
