name: seocheck
version: 0.1.0.0
github: "NorfairKing/seocheck"
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2020-2024 Tom Sydney Kerckhove"
license: MIT
synopsis: Check for common SEO mistakes on CI

extra-source-files:
- LICENSE
- CHANGELOG.md
- test_resources/**/*

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - case-insensitive
    - conduit
    - containers
    - html-conduit
    - http-client
    - http-client-tls
    - http-types
    - monad-logger
    - network-uri
    - opt-env-conf
    - path
    - path-io
    - pretty-show
    - safe-coloured-text
    - safe-coloured-text-terminfo
    - stm
    - text
    - unliftio
    - validity
    - xml-conduit

executables:
  seocheck:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - seocheck

tests:
  seocheck-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - opt-env-conf-test
    - sydtest
    - seocheck
