resolver: lts-22.22
packages:
- seocheck
extra-deps:
- github: NorfairKing/opt-env-conf
  commit: 14d502e235923daaf39d746c861869a6cdd8a890
  subdirs:
    - opt-env-conf
    - opt-env-conf-test

- github: NorfairKing/safe-coloured-text
  commit: 26b7657428f277f819a0831cbddddb7f4c5408f9
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-layout
    - safe-coloured-text-terminfo

- github: NorfairKing/autodocodec
  commit: c51eaad56acb0f9e6fa68ae7c1a14ba9dd8650c6
  subdirs:               
    - autodocodec
    - autodocodec-nix
    - autodocodec-schema  
    - autodocodec-yaml                            
system-ghc: true
nix:
  enable: false
with-hpack: hpack
